### ISSUE TITLE
4 mis-matches on the Monthly Report

### ISSUE THREAD

**Issue by chengguangnan** [Crowdpac/analytics#3]
Hi @fvelloso ,

There are 4 mis-matches on https://docs.google.com/spreadsheets/d/1Xi9vSWcUQkB5CaWQ_ILBvN4amPccidyhQ6Zly0eaXv8/edit#gid=1367533105

Here is a screenshot. 

<img width="862" alt="screen shot 2018-01-24 at 6 57 51 pm" src="https://user-images.githubusercontent.com/861069/35328815-96132130-0138-11e8-9199-d6962e8037e0.png">

1) I used the same R code for calculation, so I can't know what may cause the mis-match. Did the old numbers come from the same R script? Do you know how to reproduce those old numbers?

2) For "Unique Donors - US", it was not in the R script so I have to wrote one based on donor_email, but there is a mis-match as well. Do you know how to reproduce the old number?

**Comment by fvelloso** [comment]
@chengguangnan on row 34 i have no idea what caused mismatch. On row 36, i think i calculated multi-campaign + slate donors. But now we're going to focus on multi-campaign, so we should use your figures. Row 23 was calculated by Ethan, and am waiting for his queries, then we can troubleshoot row 39.
